version: "3.7"

services:
  postgres:
    container_name: postgres-compose
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-Hello123!}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - network-compose
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin-compose-np
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-user@domain.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-Hello123!}
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - network-compose
    restart: unless-stopped
    depends_on:
      - postgres
  
  zvoga-be:
    container_name: zvoga-be-compose
    image: bencami/zvoga-be
    ports:
      - "5000:80"
    networks:
      - network-compose
    restart: unless-stopped

  zvoga-fe:
    container_name: zvoga-fe-compose
    image: bencami/zvoga-fe
    ports:
      - "3000:80"
    networks:
      - network-compose
    restart: unless-stopped

  nginx: 
    image: nginx:latest
    container_name: nginx-compose
    volumes:
      - ./etc/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443

networks:
  network-compose:
    driver: bridge

volumes:
  postgres:
  pgadmin:
