version: "3.7"

services:
  postgres:
    container_name: postgres-compose-np
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=Numberplates
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped


volumes:
  postgres: