// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NumberPlates.Data;

namespace NumberPlates.Migrations
{
    [DbContext(typeof(NumberPlateDbContext))]
    partial class NumberPlateDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("NumberPlates.Data.Entities.CommentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<int>("NumberPlateId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("NumberPlateId");

                    b.ToTable("comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comment = "Doesn't know what an indicator is.",
                            IpAddress = "12.3.4",
                            NumberPlateId = 1,
                            Timestamp = new DateTime(2020, 12, 8, 0, 0, 0, 0, DateTimeKind.Local)
                        });
                });

            modelBuilder.Entity("NumberPlates.Data.Entities.NumberPlateEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("NumberPlate")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("NumberPlate")
                        .IsUnique();

                    b.ToTable("numberplates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NumberPlate = "COR 010"
                        });
                });

            modelBuilder.Entity("NumberPlates.Data.Entities.CommentEntity", b =>
                {
                    b.HasOne("NumberPlates.Data.Entities.NumberPlateEntity", "NumberPlate")
                        .WithMany("Comments")
                        .HasForeignKey("NumberPlateId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("NumberPlate");
                });

            modelBuilder.Entity("NumberPlates.Data.Entities.NumberPlateEntity", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
